export const FORM_ON_CHANGE = 'FORM_ON_CHANGE'
export const APPLICATION_TYPE_CHANGE = "APPLICATION_TYPE_CHANGE"
export const EVIRONMENT_CHANGE = "EVIRONMENT_CHANGE"
export const LOADING_CHANGE = 'LOADING_CHANGE'
export const ON_VM_LIST_UPDATE = 'ON_VM_LIST_UPDATE'
export const STACK_CHANGE = "STACK_CHANGE"
